/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package wordmason;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Nik
 */
public class WordMasonGUI extends javax.swing.JFrame {

    /**
     * Creates new form NumberAdditionGUI
     */
    public WordMasonGUI() {
        //WordMason WM = new WordMason();
        initComponents();
        
        wallFields = new JTextField[16];
        wallFields[0] = wallField1;
        wallFields[1] = wallField2;
        wallFields[2] = wallField3;
        wallFields[3] = wallField4;
        wallFields[4] = wallField5;
        wallFields[5] = wallField6;
        wallFields[6] = wallField7;
        wallFields[7] = wallField8;
        wallFields[8] = wallField9;
        wallFields[9] = wallField10;
        wallFields[10] = wallField11;
        wallFields[11] = wallField12;
        wallFields[12] = wallField13;
        wallFields[13] = wallField14;
        wallFields[14] = wallField15;
        wallFields[15] = wallField16;
        
        setBank("ABCDEFGHIJKLMNOPQRS");
        toggleGameState(false);
        CL = new client();
        CL.setGUI(this);    // lets client know to talk to this GUI

        // TODO: create constructor, destructor, connect in client
        String[] args = new String[2];  // needed for main of client
        // args[0] = "host";  // set for non-default host. default is 127.0.0.1
        // args[1] = "port";  // set for non-default port. default is 5000
        CL.main(args); // GUI program hangs if client cannot connect
    }
    
    private int wallHeight = 0;
    private JTextField[] wallFields;
    private String currBankLetters;
    private String nextBankLetters;
    private client CL;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        nextBankLabel = new javax.swing.JLabel();
        nextBank = new javax.swing.JLabel();
        playerTwoScoreLabel = new javax.swing.JLabel();
        playerOneScoreLabel = new javax.swing.JLabel();
        playerTwoScore = new javax.swing.JLabel();
        playerOneScore = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        wallField16 = new javax.swing.JTextField();
        wallField15 = new javax.swing.JTextField();
        wallField14 = new javax.swing.JTextField();
        wallField13 = new javax.swing.JTextField();
        wallField12 = new javax.swing.JTextField();
        wallField11 = new javax.swing.JTextField();
        wallField10 = new javax.swing.JTextField();
        wallField9 = new javax.swing.JTextField();
        wallField8 = new javax.swing.JTextField();
        wallField7 = new javax.swing.JTextField();
        wallField6 = new javax.swing.JTextField();
        wallField5 = new javax.swing.JTextField();
        wallField4 = new javax.swing.JTextField();
        wallField3 = new javax.swing.JTextField();
        wallField2 = new javax.swing.JTextField();
        wallField1 = new javax.swing.JTextField();
        currBankLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        startQuitButton = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextBankLabel.setText("Next bank in x seconds:");

        nextBank.setText("A B C D E F G H I J K L M N O P Q R S");

        playerTwoScoreLabel.setText("<html> Opponent <br> score </html>");

        playerOneScoreLabel.setText("<html> Your <br> score </html>");

        playerTwoScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerTwoScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerTwoScore.setText("Y");

        playerOneScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerOneScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerOneScore.setText("X");

        wallField16.setEditable(false);
        wallField16.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField15.setEditable(false);
        wallField15.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField14.setEditable(false);
        wallField14.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField13.setEditable(false);
        wallField13.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField12.setEditable(false);
        wallField12.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField11.setEditable(false);
        wallField11.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField10.setEditable(false);
        wallField10.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField9.setEditable(false);
        wallField9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField8.setEditable(false);
        wallField8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField7.setEditable(false);
        wallField7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField6.setEditable(false);
        wallField6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField5.setEditable(false);
        wallField5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField4.setEditable(false);
        wallField4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField3.setEditable(false);
        wallField3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField2.setEditable(false);
        wallField2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        wallField1.setEditable(false);
        wallField1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        wallField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wallField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        currBankLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        currBankLabel.setText("A B C D E F G H I J K L M N O P Q R S");
        currBankLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wallField16, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField15, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField14, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField13, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField12, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField11, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(wallField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(currBankLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(currBankLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wallField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wallField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonPressed(evt);
            }
        });

        startQuitButton.setText("Start/Quit");
        startQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startQuitButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerOneScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(playerOneScore)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerTwoScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(playerTwoScore))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nextBankLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nextBank))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startQuitButton)
                                .addGap(81, 81, 81)
                                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBankLabel)
                    .addComponent(nextBank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(startQuitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(playerOneScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerOneScore))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(playerTwoScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerTwoScore)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

   
    
    private void startQuitButtonPressed(java.awt.event.ActionEvent evt) {                                        
        String buttonText = startQuitButton.getText();
        if (buttonText.equals("Start")) {
            CL.update(0);
            toggleGameState(true);
        } else {
            CL.update(4);
            toggleGameState(false);
        }
    }                                       

    public void submitWord(String word) {
        currBankLetters = currBankLetters.toLowerCase();
        word = word.toLowerCase();
        char[] bankChars = currBankLetters.toCharArray();
        char[] wordChars = word.toCharArray();
        int lettersUsed = 0;
        for (int i = 0; i < bankChars.length; i++) {
            char bankLetter = bankChars[i];
            for(int j = 0; j < word.length(); j++) {
                char wordLetter = wordChars[j];
                if (bankLetter != ' ' && bankLetter == wordLetter) {
                    bankChars[i] = ' ';
                    wordChars[j] = ' ';
                    lettersUsed++;
                    break;
                }
            }
        }
        
        if (lettersUsed != word.length()) {
            inputField.setText("Invalid");
        } else {
            CL.word(word);
            //addWord(word);
        }
    }
    
    private void submitButtonPressed(java.awt.event.ActionEvent evt) {                                     
        String word = inputField.getText();
        submitWord(word);
    }                                    

    public void setBank(String letters) {
        currBankLetters = letters;
        currBankLabel.setText(currBankLetters);
    }
    
    public void setNextBank(String letters) {
        nextBankLetters = letters;
    }
    
    public void setPlayerOneScore(int score) {
        playerOneScore.setText(Integer.toString(score));
    }
    
    public void setPlayerTwoScore(int score) {
        playerTwoScore.setText(Integer.toString(score));
    }
    
    public void addWord(String word) {
        wallFields[wallHeight].setText(word);
        wallHeight++;
        
        currBankLetters = currBankLetters.toLowerCase();
        word = word.toLowerCase();
        char[] bankChars = currBankLetters.toCharArray();
        char[] wordChars = word.toCharArray();
        for (int i = 0; i < bankChars.length; i++) {
            char bankLetter = bankChars[i];
            for(int j = 0; j < word.length(); j++) {
                char wordLetter = wordChars[j];
                if (bankLetter != ' ' && bankLetter == wordLetter) {
                    bankChars[i] = ' ';
                    wordChars[j] = ' ';
                    break;
                }
            }
        }
        setBank(String.valueOf(bankChars));
    }
    
    public void timeOutDialog() {
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "Connection timed out.");
    }
    
    public void gameOverDialog() {
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "Game over!");
        toggleGameState(false);
    }
    
    private void toggleGameState(boolean toggle) {
        submitButton.setEnabled(toggle);
        inputField.setEnabled(toggle);
        
        for (int i = 0; i < wallFields.length; i++) {
            wallFields[i].setEnabled(toggle);
        }
        if (toggle == true) {
            startQuitButton.setText("Quit");
        } else {
            startQuitButton.setText("Start");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordMasonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordMasonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordMasonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordMasonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordMasonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel currBankLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nextBank;
    private javax.swing.JLabel nextBankLabel;
    private javax.swing.JLabel playerOneScore;
    private javax.swing.JLabel playerOneScoreLabel;
    private javax.swing.JLabel playerTwoScore;
    private javax.swing.JLabel playerTwoScoreLabel;
    private javax.swing.JButton startQuitButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField wallField1;
    private javax.swing.JTextField wallField10;
    private javax.swing.JTextField wallField11;
    private javax.swing.JTextField wallField12;
    private javax.swing.JTextField wallField13;
    private javax.swing.JTextField wallField14;
    private javax.swing.JTextField wallField15;
    private javax.swing.JTextField wallField16;
    private javax.swing.JTextField wallField2;
    private javax.swing.JTextField wallField3;
    private javax.swing.JTextField wallField4;
    private javax.swing.JTextField wallField5;
    private javax.swing.JTextField wallField6;
    private javax.swing.JTextField wallField7;
    private javax.swing.JTextField wallField8;
    private javax.swing.JTextField wallField9;
    // End of variables declaration                   
}
